bdsm_django/urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from django.contrib import admin
import django_app.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(django_app.urls)),
]

django_app/urls.py
from __future__ import unicode_literals
from django.conf.urls import url
import views

app_name = 'django_app'
urlpatterns = [
    url(r'change_password$', views.change_password,
        name='change_password'),
    url(r'all_ready_not_returned_orders$', views.all_ready_not_returned_orders,
        name='all_ready_not_returned_orders'),
    url(r'create_user$', views.create_user,
        name='create_user'),
    url(r'create_client$', views.create_client,
        name='create_client'),
    url(r'create_bonus$', views.create_bonus,
        name='create_bonus'),
    url(r'create_discount$', views.create_discount,
        name='create_discount'),
    url(r'create_service$', views.create_service,
        name='create_service'),
    url(r'update_service/([0-9]+)$', views.update_service,
        name='update_service'),
    url(r'get_bonuses$', views.get_bonuses,
        name='get_bonuses'),
    url(r'update_bonus/([0-9]+)$', views.update_bonus,
        name='update_bonus'),
    url(r'get_discounts$', views.get_discounts,
        name='get_discounts'),
    url(r'update_discount/([0-9]+)$', views.update_discount,
        name='update_discount'),
    url(r'create_office$', views.create_office,
        name='create_office'),
    url(r'update_office/([0-9]+)$', views.update_office,
        name='update_office'),

    # url(r'edit_order/([0-9]+)$', views.edit_order,
    #     name='edit_order'),
    url(r'return_order/([0-9]+)$', views.return_order,
        name='return_order'),
    url(r'set_order_ready_status/([0-9]+)$', views.set_order_ready_status,
        name='set_order_ready_status'),
    url(r'update_client/([0-9]+)$', views.update_client,
        name='update_client'),
    url(r'clients$', views.get_clients,
        name='clients'),
    url(r'offices$', views.get_offices,
        name='offices'),
    url(r'order/([0-9]+)$', views.get_order_info,
        name='order'),
    url(r'check_order$', views.check_order,
        name='check_order'),
    url(r'client_orders/([0-9]+)$', views.client_orders,
        name='client_orders'),
    url(r'check_client_order$', views.check_client_orders,
        name='check_client_orders'),
    url(r'client_orders_ready_not_returned/([0-9]+)$', views.client_orders_ready_not_returned,
        name='ready_not_returned_orders'),
    url(r'check_order_ready_not_returned$', views.check_client_orders_ready_not_returned,
        name='check_client_orders_ready_not_returned'),
    url(r'client_info/([0-9]+)$', views.client_info,
        name='client_info'),
    url(r'check_client_info$', views.check_client_info,
        name='check_client_info'),
    url(r'logout$', views.logout,
        name='logout'),
    url(r'login$', views.login,
        name='login'),
    url(r'register$', views.register,
        name='register'),
    url(r'services$', views.services,
        name='services'),
    url(r'add_order$', views.order,
        name='add_order'),
    url(r'all_orders$', views.all_orders,
        name='all_orders'),
    url(r'$', views.index,
        name='index'),
]

django_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

django_app/forms.py
from __future__ import unicode_literals
from django import forms
from list_requests import list_request


class OrderIdForm(forms.Form):
    order_id = forms.IntegerField(label='Order id\n', min_value=1)


class ClientIdForm(forms.Form):
    client_id = forms.IntegerField(label='Client id\n', min_value=1)


class LoginForm(forms.Form):
    login = forms.CharField(label='Login ', required=True)
    password = forms.CharField(widget=forms.PasswordInput, label='Password ')


class RegistrationForm(forms.Form):
    login = forms.CharField(label='Login ', required=True)
    password = forms.CharField(widget=forms.PasswordInput, label='Password ', required=True)
    client_id = forms.IntegerField(label='Client ID ', min_value=1, required=True)


def split_id(data):
    id_ = []
    for i, element in enumerate(data):
        data[i] = element[1:]
        id_[i] = element[0]
    return id_, data


class OrderForm(forms.Form):
    client_id = forms.ChoiceField(label='Client ', required=True)
    service_type_id = forms.ChoiceField(label='Service type ', required=True)
    service_bonus_id = forms.ChoiceField(label='Service bonus', required=False)
    amount = forms.IntegerField(label='Amount ', min_value=1, required=True)
    office_id = forms.ChoiceField(label='Office', required=True)
    discount_type_id = forms.ChoiceField(label='Discount ', required=True)

    def __init__(self, *args, **kwargs):
        request = None
        if 'request' in kwargs.keys():
            request = kwargs['request']
            del kwargs['request']
        super(OrderForm, self).__init__(*args, **kwargs)
        if request:

            _, data = list_request(request, 'get_service_types')
            self.fields['service_type_id'].choices = [(int(element[0]), ' '.join(map(str, element[1:]))) for element in data]

            _, data = list_request(request, 'get_bonuses')
            self.fields['service_bonus_id'].choices = [(int(element[0]), ' '.join(map(str, element[1:]))) for element in data] + [(None, "None")]

            _, data = list_request(request, 'get_clients')
            self.fields['client_id'].choices = [(int(element[0]), ' '.join(map(str, element[1:]))) for element in data]

            _, data = list_request(request, 'get_discount_types')
            self.fields['discount_type_id'].choices = [(int(element[0]), ' '.join(map(str, element[1:]))) for element in data]  + [(None, "None")]

            _, data = list_request(request, 'get_offices')
            self.fields['office_id'].choices = [(int(element[0]), ' '.join(map(str, element[1:]))) for element in data]


class OrderFormToValidate(forms.Form):
    client_id = forms.IntegerField(label='Client ', required=True)
    service_type_id = forms.IntegerField(label='Service type ', required=True)
    service_bonus_id = forms.IntegerField(label='Service bonus', required=False)
    amount = forms.IntegerField(label='Amount ', min_value=1, required=True)
    office_id = forms.IntegerField(label='Office', required=True)
    discount_type_id = forms.IntegerField(label='Discount ', required=False, min_value=1)


class ClientForm(forms.Form):
    first_name = forms.CharField(label='First Name', required=True)
    last_name = forms.CharField(label='Last name', required=True)
    # best_client = forms.ChoiceField(label='Best client', choices=[(1, 'True'), (0, 'False')])


class ChangePasswordForm(forms.Form):
    password_1 = forms.CharField(widget=forms.PasswordInput, label='Password new')
    password_2 = forms.CharField(widget=forms.PasswordInput, label='Password new')


class CreateUserForm(forms.Form):
    login = forms.CharField(required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)
    role = forms.ChoiceField(required=True, choices=[[1,'admin'], [2,'worker'], [3,'user']])


class BonusForm(forms.Form):
    type = forms.CharField(required=True, label='Type ')
    value = forms.FloatField(min_value=0, max_value=100, label='Bonus value', required=True)


class DiscountForm(forms.Form):
    description = forms.CharField(required=True, label='Type ')
    value = forms.FloatField(min_value=0, max_value=100, label='Bonus value', required=True)


class ServiceForm(forms.Form):
    name = forms.CharField(required=True, label='Name ')
    price = forms.FloatField(min_value=0, label='Base price ', required=True)


class OfficeForm(forms.Form):
    location = forms.CharField(required=True, label='Location ')
    description = forms.CharField(label='Description ', required=True)

django_app/views.py
from __future__ import print_function
from __future__ import unicode_literals
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse
from list_requests import list_request
from .forms import OrderIdForm, ClientIdForm, LoginForm,\
    RegistrationForm, OrderForm, OrderFormToValidate, ClientForm,\
    ChangePasswordForm, CreateUserForm, BonusForm, DiscountForm, ServiceForm, OfficeForm
from registraton_authorization import login as logging_in
from registraton_authorization import register as register_in_db
from registraton_authorization import insert_order ,\
    return_order as set_order_status_to_returned,\
    set_order_ready, update_client as update_client_in_db,\
    update_user_password, create_user_in_db, create_bonus_in_db,\
    call_function_in_db, call_procedure_in_db

from errors import AccessDeniedError


def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            p1 = form.cleaned_data['password_1']
            p2 = form.cleaned_data['password_2']
            if p1 == p2:
                if update_user_password(request, request.COOKIES['username'], p1):
                    return render(request, 'django_app/index.html', {'message': 'changed!'})
        return render(request, 'django_app/update_pass_form.html', {'form': form, 'message': 'invalid_form'})
    else:
        form = ChangePasswordForm()
        return render(request, 'django_app/update_pass_form.html', {'form' : form})


def get_clients(request):
    try:
        row_names, data = list_request(request, 'get_clients')
    except AccessDeniedError:
        return render(request, 'django_app/client_list.html',
                  {"error": True})
    extra_thing = {'url': 'django_app:update_client', 'text': 'Update client'}
    return render(request, 'django_app/client_list.html',
                  {"headers": row_names, "data": data, "error" : False, 'extra_thing' : extra_thing})


def update_client(request, client_id):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            if update_client_in_db(request, first_name, last_name, client_id):
                resp = HttpResponseRedirect(reverse('django_app:index'))
                resp.write(render(request, 'django_app/index.html', {'message': 'client updated'}))
                return resp
            else:
                resp = HttpResponseRedirect(reverse('django_app:index'))
                resp.write(render(request, 'django_app/index.html', {'message': 'Error while updating'}))
                return resp
        return render(request, 'django_app/client_form.html', {'form': form, 'id': client_id})

    else:
        row_names, record = list_request(request, 'client_info', [int(client_id)])
        form = ClientForm(data={'first_name': record[0][1], 'last_name': record[0][2], 'best_client': record[0][3]})
        return render(request, 'django_app/client_form.html', {'form': form, 'id' : record[0][0]})


def client_info(request, client_id):
    try:
        row_names, data = list_request(request, 'client_info', [int(client_id)])
        is_ready_index = row_names.index('Best client')
        for i, element in enumerate(data):
            data[i] = list(data[i])
            data[i][is_ready_index] = bool(element[is_ready_index])
            extra_thing = {'url': 'django_app:update_client', 'text': 'Update client'}
        return render(request, 'django_app/client_info.html',
                      {"headers": row_names, "data": data, 'extra_thing': extra_thing})
    except AccessDeniedError:
        return render(request, 'django_app/client_info.html',
                      {"error": True})


def get_offices(request):
    try:
        row_names, data = list_request(request, 'get_offices')
        extra_thing = None
        if 'connection' in request.COOKIES and request.COOKIES['connection'] == 'admin':
            extra_thing = {'url': 'django_app:update_office', 'text': 'Update office'}
        return render(request, 'django_app/list_template.html',
                      {"headers": row_names, "data": data, 'extra_thing': extra_thing})
    except AccessDeniedError:
        return render(request, 'django_app/list_template.html',
                      {"error": True})


def update_office(request, office_id):
    if request.method == 'POST':
        form = OfficeForm(request.POST)
        if form.is_valid():
            description = form.cleaned_data['location']
            value = form.cleaned_data['description']
            if call_procedure_in_db(request, 'update_office_by_id', [int(office_id), description, value]):
                return render(request, 'django_app/index.html', {'message': 'office updated'})
            else:
                return render(request, 'django_app/index.html', {'message': 'Error while updating'})
        return render(request, 'django_app/edit_form_template.html',
                      {'form': form, 'id': office_id,
                       'url_': 'django_app:update_office'})

    else:
        row_names, record = list_request(request, 'get_office_by_id', [int(office_id)])
        form = OfficeForm(data={'location': record[0][1], 'description': record[0][2]})
        return render(request, 'django_app/edit_form_template.html', {'form': form, 'id': office_id,
                                                                      'url_': 'django_app:update_office'})


def index(request):
    return render(request, 'django_app/index.html')


def get_order_info(request, order_id):
    try:
        row_names, data = list_request(request, 'get_order_info', [int(order_id)])
        is_ready_index = row_names.index('Is ready')
        for i, element in enumerate(data):
            data[i] = list(data[i])
            data[i][is_ready_index] = bool(element[is_ready_index])

        return render(request, 'django_app/order_status.html',
                      {"headers": row_names, "data": data})
    except AccessDeniedError:
        return render(request, 'django_app/order_status.html',
                      {"error" : True})


def check_order(request):
    if request.method == 'POST':
        form = OrderIdForm(request.POST)
        if form.is_valid():
            order_id = form.cleaned_data['order_id']
            return HttpResponseRedirect(reverse('django_app:order', args=(order_id,)))
    else:
        form = OrderIdForm()
        return render(request, 'django_app/check_order.html', {"form": form})


def client_orders(request, client_id):
    try:
        row_names, data = list_request(request, 'client_orders', [int(client_id)])
        is_ready_index = row_names.index('Is ready')
        for i, element in enumerate(data):
            data[i] = list(data[i])
            data[i][is_ready_index] = bool(element[is_ready_index])

        return render(request, 'django_app/client_orders_list.html',
                      {"headers": row_names, "data": data})
    except AccessDeniedError:
        return render(request, 'django_app/client_orders_list.html',
                      {"error": True})


def check_client_orders(request):
    if request.method == 'POST':
        form = ClientIdForm(request.POST)
        if form.is_valid():
            client_id = form.cleaned_data['client_id']
            return HttpResponseRedirect(reverse('django_app:client_orders', args=(client_id,)))
    else:
        form = ClientIdForm()
        return render(request, 'django_app/check_client_orders.html', {"form": form})


def all_ready_not_returned_orders(request):
    try:
        row_names, data = list_request(request, 'get_ready_not_returned_orders')
        is_ready_index = row_names.index('Is ready')
        for i, element in enumerate(data):
            data[i] = list(data[i])
            data[i][is_ready_index] = bool(element[is_ready_index])
        extra_thing = None
        if 'connection' in request.COOKIES and request.COOKIES['connection'] == 'worker':
            extra_thing = {'url': 'django_app:return_order', 'text': 'Return'}
        return render(request, 'django_app/orders_ready_not_returned_list.html',
                      {"headers": row_names, "data": data, 'extra_thing': extra_thing})
    except AccessDeniedError:
        return render(request, 'django_app/orders_ready_not_returned_list.html',
                      {"error": True})


def client_orders_ready_not_returned(request, client_id):
    try:
        row_names, data = list_request(request, 'ready_not_returned', [int(client_id)])
        is_ready_index = row_names.index('Is ready')
        for i, element in enumerate(data):
            data[i] = list(data[i])
            data[i][is_ready_index] = bool(element[is_ready_index])
        extra_thing = None
        if 'connection' in request.COOKIES and request.COOKIES['connection'] == 'worker':
            extra_thing = {'url': 'django_app:return_order', 'text': 'Return'}
        return render(request, 'django_app/orders_ready_not_returned_list.html',
                      {"headers": row_names, "data": data, 'extra_thing': extra_thing})
    except AccessDeniedError:
        return render(request, 'django_app/orders_ready_not_returned_list.html',
                      {"error": True})


def check_client_orders_ready_not_returned(request):
    if request.method == 'POST':
        form = ClientIdForm(request.POST)
        if form.is_valid():
            client_id = form.cleaned_data['client_id']
            return HttpResponseRedirect(reverse('django_app:ready_not_returned_orders', args=(client_id,)))
    else:
        form = ClientIdForm()
        return render(request, 'django_app/check_orders_ready_not_returned.html', {"form": form})


def check_client_info(request):
    if request.method == 'POST':

django_app/templates/django_app/bonus_form.html
{% extends 'django_app/base_template.html' %}
{% block title %}Create user{% endblock %}
{% block content %}

<form action="{% url 'django_app:create_bonus' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="Create">
</form>

{% endblock %}

django_app/templates/django_app/client_form.html
{% extends 'django_app/base_template.html' %}
{% block title %}Client updating{% endblock %}
{% block content %}

<form action="{% url 'django_app:update_client' id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="send">
</form>

{% endblock %}

django_app/templates/django_app/client_info.html
{% extends 'django_app/list_template.html' %}
{% block title %}Client{% endblock %}
{% block header %}Client information{% endblock %}
{% block not_found %}No client{% endblock %}

django_app/templates/django_app/client_orders_list.html
{% extends "django_app/list_template.html" %}
{% block title %}ClientList{% endblock %}
{% block header %}Order of client{% endblock %}
{% block not_found %}No orders{% endblock %}

django_app/templates/django_app/create_user_form.html
{% extends 'django_app/base_template.html' %}
{% block title %}Create user{% endblock %}
{% block content %}

<form action="{% url 'django_app:create_user' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="Create">
</form>

{% endblock %}

django_app/templates/django_app/edit_form_template.html
{% extends 'django_app/base_template.html' %}
{% block title %}Create user{% endblock %}
{% block content %}

    {% if message %}
        <h3 class="header">{{ message }}</h3>
    {% endif %}
<form action="{% url url_ id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="Create">
</form>

{% endblock %}

django_app/templates/django_app/form_template.html
{% extends 'django_app/base_template.html' %}
{% block title %}Create user{% endblock %}
{% block content %}

    {% if message %}
        <h3 class="header">{{ message }}</h3>
    {% endif %}
<form action="{% url url_ %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="Create">
</form>

{% endblock %}

django_app/templates/django_app/list_template.html
{% extends "django_app/base_template.html" %}
{% block title %}{% endblock %}
{% block content %}
{% if error %}
    <h2 class="header">Access denied, peach!</h2>
{% else %}
    {% if data %}
        <h2 class="header">{% block header %}{% endblock %}</h2>
        <table class="table table-bordered">
            <thead>
                <tr>
                    {% for header_name in headers %}
                        <td style="font-weight: bold">{{ header_name }}</td>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>

            {% for record in data %}
                <tr>
                {% for record_value in record %}
                    <td>{{ record_value }}</td>
                {% endfor %}
                {% if extra_thing %}
                    <td><a href="{% url extra_thing.url record.0 %}">{{ extra_thing.text}}</a></td>
                {% endif %}
                </tr>
            {% endfor %}
            </tbody>

        </table>
    {% else %}
       <h2 class="header">{% block not_found %}{% endblock %}</h2>
    {% endif %}
{% endif %}
{% endblock %}

django_app/templates/django_app/login_form.html
{% extends 'django_app/base_template.html' %}
{% block title %}Login{% endblock %}

{% block content %}
    {% if message %}
        <h2 class="header">{{ message }}</h2>
    {% endif %}
    <form action="{% url 'django_app:login' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn" value="Login" type="submit">
    </form>

{% endblock %}

django_app/templates/django_app/offices_list.html
{% extends "django_app/list_template.html" %}
{% block title %}Offices list{% endblock %}
{% block header %}All offices{% endblock %}
{% block not_found %}No offices found{% endblock %}

django_app/templates/django_app/orders_list.html
{% extends "django_app/base_template.html" %}
{% block title %}Orders list{% endblock %}
{% block content %}
{% if error %}
    <h2 class="header">Access denied, peach!</h2>
{% else %}
    {% if data %}
        <h2 class="header">{% block header %}{% endblock %}</h2>
        <table class="table table-bordered">
            <thead>
                <tr>
                    {% for header_name in headers %}
                        <td style="font-weight: bold">{{ header_name }}</td>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>

            {% for record in data %}
                <tr>
                {% for record_value in record %}
                    <td>{{ record_value }}</td>
                {% endfor %}
{#                <td><a href="{% url 'django_app:edit_order' record.0 %}">Edit</a></td>#}
                <td><a href="{% url 'django_app:set_order_ready_status' record.0  %}">Set ready</a></td>
                <td><a href="{% url 'django_app:return_order' record.0  %}">Return order</a></td>

                </tr>
            {% endfor %}
            </tbody>

        </table>
    {% else %}
       <h2 class="header">{% block not_found %}{% endblock %}</h2>
    {% endif %}
{% endif %}
{% endblock %}

django_app/templates/django_app/orders_ready_not_returned_list.html
{% extends "django_app/list_template.html" %}
{% block title %}Ready orders{% endblock %}
{% block header %}Ready{% endblock %}
{% block not_found %}No such orders{% endblock %}

django_app/templates/django_app/service_types_list.html
{% extends 'django_app/list_template.html' %}
{% block title %}Services{% endblock %}
{% block header %}Services available{% endblock %}
{% block  not_found %}No services found{% endblock %}

django_app/templates/django_app/update_pass_form.html
{% extends 'django_app/base_template.html' %}
{% block title %}Client updating{% endblock %}
{% block content %}
    {% if message %}
        <h2 class="header">{{ message }}</h2>
    {%  endif %}
<form action="{% url 'django_app:change_password' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="send">
</form>

{% endblock %}